// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:23224d53-a11c-4e52-a708-4a12a8113e48",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_a13Fy43KW",
    "aws_user_pools_web_client_id": "4mqifljjrqm5lakq1h9nkrb8p3",
    "aws_user_files_s3_bucket": "4milkapp7775955879aa48e891e361b5e262104e",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
